// MFCApplicationHandlers.idl : IDL source for MFCApplicationHandlers
//

// This file will be processed by the MIDL tool to
// produce the type library (MFCApplicationHandlers.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(22cc8c7c-1ae0-447a-8642-9a00894a6722),
	pointer_default(unique)
]
interface IPreview : IUnknown
{
};

[
	object,
	uuid(eed01141-19f2-4474-aa6a-704567c7f939),
	pointer_default(unique)
]
interface IThumbnail : IUnknown
{
};

[
	object,
	uuid(a68b09e0-7d1b-4d5a-a104-de6d8d9bd163),
	pointer_default(unique)
]
interface ISearch : IUnknown
{
};

[
	uuid(6ce6bb9b-7b2c-4d82-87b5-1c3e8a1db86a),
	version(1.0),
]
library MFCApplicationHandlersLib
{
	importlib("stdole2.tlb");
	[
		uuid(9d4f2969-31f4-4dd2-ba7e-44868910c832)
	]
	coclass Preview
	{
		[default] interface IPreviewHandler;
	};
	[
		uuid(a24e0c64-2ba1-4c57-839c-399dab7cfd81)
	]
	coclass Thumbnail
	{
		[default] interface IThumbnailProvider;
	};
	[
		uuid(2f5c49bf-31cf-4c76-9ab3-abeff3d5e10c)
	]
	coclass Search
	{
		[default] interface IFilter;
	};
};

import "shobjidl.idl";
import "thumbcache.idl";
import "filter.idl";
