// MFCApplication.idl : type library source for MFCApplication.exe

// This file will be processed by the MIDL compiler to produce the
// type library (MFCApplication.tlb).

[ uuid(6ce6bb9b-7b2c-4d82-87b5-1c3e8a1db86a), version(1.0) ]
library MFCApplication
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  Primary dispatch interface for CMFCApplicationDoc

	[ uuid(faa7acdb-56e2-45eb-a130-11f9ff12a57f) ]
	dispinterface IMFCApplication
	{
		properties:

		methods:
	};

	//  Class information for CMFCApplicationDoc

	[ uuid(a589a381-8c85-4fb3-8596-eb25cb7b8c90) ]
	coclass CMFCApplicationDoc
	{
		[default] dispinterface IMFCApplication;
	};
};
